# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token af59613cf76987dc001bf04d93b3c787a2951430

{
  "title": "Шкаф 99",
  "description": "Срочно"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/37/
Content-Type: application/json
Authorization: Token af59613cf76987dc001bf04d93b3c787a2951430

{
  "title": "Шкаф 11",
  "description": "Срочно"
}
###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/16/
Content-Type: application/json
Authorization: Token af59613cf76987dc001bf04d93b3c787a2951430

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-10-31
Content-Type: application/json

###

4d47e8033b623153c5bb405d3a4a81a7dcb4a5cf
af59613cf76987dc001bf04d93b3c787a2951430
