# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token af59613cf76987dc001bf04d93b3c787a2951430

{
  "title": "Шкаф 11",
  "description": "Срочно"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/23/
Content-Type: application/json
Authorization: Token af59613cf76987dc001bf04d93b3c787a2951430

{
  "title": "Шкаф 11",
  "description": "Срочно"
}
###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token af59613cf76987dc001bf04d93b3c787a2951430

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
